# Generated by Django 5.0.2 on 2024-03-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementCourseApp', '0011_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
