# Generated by Django 5.0.2 on 2024-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementCourseApp', '0013_alter_course_tags_alter_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=255, null=True),
        ),
    ]
