# Generated by Django 5.0.2 on 2024-04-03 05:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementCourseApp', '0016_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
