# Generated by Django 5.0.2 on 2024-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementCourseApp', '0008_alter_like_active_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
