# Generated by Django 5.0.2 on 2024-03-31 04:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementCourseApp', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
